Public Class RekamMedisBumil
    Public Property kd_rm As String
    Public Property tgl_rm As Date
    Public Property posyandu As String
    Public Property nm_kader As String
    Public Property nm_dukun As String
    Public Property jamkesmas As String
    Public Property gol_darah As String
    Public Property granida As String
    Public Property partis As String
    Public Property aborus As String
    Public Property hidup As String
    Public Property tgl_periksa As Date
    Public Property tgl_hpht As Date
    Public Property taksiran_persalinan As Date
    Public Property bb_sblm_hamil As String
    Public Property tb As String
    Public Property buku_kia As String
    Public Property riwayat_komplikasi_kebidanan As String
    Public Property penyakit_kronis_alergi As String
    Public Property tgl_persalinan As Date
    Public Property penolong As String
    Public Property tempat As String
    Public Property pendamping As String
    Public Property transportasi As String
    Public Property pendonor As String
    Public Property cara_masuk As String
    Public Property usia_kelinis As String
    Public Property transfer_ke As String
    Public Property anamnesia As String
    Public Property bb As String
    Public Property td As String
    Public Property status_gizi As String
    Public Property tfu As String
    Public Property refleks_patella As String
    Public Property djj As String
    Public Property kepala_thd_pap As String
    Public Property tbj As String
    Public Property presentasi As String
    Public Property jumlah_janin As String
    Public Property status_imunisasi As String
    Public Property catat_dibuku_kia As String
    Public Property fe As String
    Public Property hb_dilakukan As String
    Public Property hb_hasil As String
    Public Property anemia As String
    Public Property pretein_urie As String
    Public Property gula_darah As String
    Public Property reduksi As String
    Public Property siphilis As String
    Public Property vct As String
    Public Property periksa_darah As String
    Public Property serologi As String
    Public Property arv As String
    Public Property therapi As String
    Public Property injeksi_tt As String
    Public Property kd_reg As String
    Public Property tgl_reg As Date
    Public Property nm_psn As String
    Public Property nm_poli As String
    Public Property nm_dok As String
    Public Property detail As String
    Public Property kd_tindakan As String
End Class

